### ISSUE TITLE
Transform /k8s folder to helm chart

### ISSUE THREAD

**Issue by Max-Levitskiy** [misterdorito/postgresql_tools#3]
We need parameters:

- create or not volume
- storage size
- image tag

**Comment by misterdorito** [comment]
See https://github.com/misterdorito/postgresql_tools_chart/blob/master/templates/pg_tools_deployment.yaml

**Comment by misterdorito** [comment]
https://github.com/misterdorito/postgresql_tools_chart -- feel free to contribute

**Comment by Max-Levitskiy** [comment]
Oh, ok. :)
